### ISSUE TITLE
CMAP InvalidFileFormatException

### ISSUE THREAD

**Issue by jluebeck** [TF-Chan-Lab/OMBlast#2]
When using the tool to align two BioNano CMAPS (v 0.1) the following error is generated:

Exception in thread "main" aldenjava.opticalmapping.miscellaneous.InvalidFileFormatException
	at aldenjava.opticalmapping.data.mappingresult.ResultFormat.lookupfileext(ResultFormat.java:83)
	at aldenjava.opticalmapping.data.mappingresult.ResultFormat.lookup(ResultFormat.java:69)
	at aldenjava.opticalmapping.data.mappingresult.OptMapResultWriter.<init>(OptMapResultWriter.java:39)
	at aldenjava.opticalmapping.data.mappingresult.OptMapResultWriter.<init>(OptMapResultWriter.java:26)
	at aldenjava.opticalmapping.mapper.Mapper.standardMapperProcedure(Mapper.java:270)
	at aldenjava.opticalmapping.mapper.omblastmapper.OMBlastMapper.main(OMBlastMapper.java:85)

Command used
java -jar /home/jens/Desktop/libs/OMBlast/OMBlast.jar --refmapin EXP_REFINEFINAL1_r.cmap --optmapin EXP_REFINEFINAL1_q.cmap --writeunmap false --refmapinformat 6 --optmapinformat 6

The BioNano CMAP files in this example are both valid as they were produced by the BioNano assembly pipeline. They are CMAP files with version 0.1.

It seems from looking at OptMapDataReader.java that the issue perhaps lies in how the parser handles the header of the file; CMAP has a header, and does not contain the field specifying total number of labels in the file as expected by the parseCMAP method.

**Comment by aldenleung** [comment]
Hi. I suppose the InvalidFileFormatException refers to the missing parameter --optresout instead. This parameter indicates where your alignment should be output. In addition, I suppose you are working on an assembly / assembly alignment and you need to optimize the parameters accordingly. Please refer to http://opticalmapping.info/alignment/ for some example.
